export default const initialState = {
  name: '',
  cedula: '',
  address: '',
  phone: '',
  email: '',
  nameIsValid: null,
  cedulaIsValid: null,
  addressIsValid: null,
  phoneIsValid: null,
  emailIsValid: null,
  nameInputChange: true,
  cedulaInputChange: true,
  addressInputChange: true,
  phoneInputChange: true,
  emailInputChange: true,
 };