const initialState = {
 name: '',
 lastName: '',
 documentType: '',
 cedula: '',
 department: '',
 city: '',
 neighborhood: '',
 address: '',
 phone: '',
 email: '',
 nameIsValid: null,
 lastNameIsValid: null,
 documentTypeIsValid: null,
 cedulaIsValid: null,
 departmentIsValid: null,
 cityIsValid: null,
 neighborhoodIsValid: null,
 addressIsValid: null,
 phoneIsValid: null,
 emailIsValid: null,
 nameInputChange: true,
 lastNameInputChange: true,
 documentTypeInputChange: true,
 cedulaInputChange: true,
 departmentInputChange: true,
 cityInputChange: true,
 neighborhoodInputChange: true,
 addressInputChange: true,
 phoneInputChange: true,
 emailInputChange: true,
};
export default initialState;
