export const products = [
 {
  productId: 1,
  productName: 'ELECTROLUX',
  productPrice: 839000,
  productImage: require('../../assets/images/aspiradora.png'),
  productDescription: 'Aspiradora 1200 W 440 W Succión',
  productSubCategory: 20,
  productColor: 'Negro',
 },
 {
  productId: 2,
  productName: 'KITCHENA',
  productPrice: 1699000,
  productImage: require('../../assets/images/batidora.png'),
  productDescription: 'batidora Artisan Metallic Chrome',
  productSubCategory: 17,
  productColor: 'Negro',
 },
 {
  productId: 3,
  productName: 'OSTER',
  productPrice: 118000,
  productImage: require('../../assets/images/cafetera.png'),
  productDescription: 'Cafetera 4 tazas BVSTDCDR5B',
  productSubCategory: 21,
  productColor: 'Negro',
 },
 {
  productId: 4,
  productName: 'GAMA',
  productPrice: 89000,
  productImage: require('../../assets/images/cortapelo.png'),
  productDescription: 'Clipper SE PRO Power 10',
  productSubCategory: 21,
  productColor: 'Negro',
 },
 {
  productId: 5,
  productName: 'OSTER',
  productPrice: 505090,
  productImage: require('../../assets/images/freidoraDeAire.png'),
  productDescription: 'Freidora de aire de 5.5 Litros CKSTAF55',
  productSubCategory: 17,
  productColor: 'Negro',
 },
 {
  productId: 6,
  productName: 'OSTER',
  productPrice: 590000,
  productImage: require('../../assets/images/OriginalLicuadora.png'),
  productDescription: 'Licuadora Kaliman 2 Vel + Pulso BLSTKAG Roja',
  productSubCategory: 17,
  productColor: 'Negro',
 },
 {
  productId: 7,
  productName: 'OSTER',
  productPrice: 249000,
  productImage: require('../../assets/images/Multiolla.png'),
  productDescription: 'Multiolla rápproductIda electrica de 5,7 lts Oster®',
  productSubCategory: 17,
  productColor: 'Negro',
 },
 {
  productId: 8,
  productName: 'OSTER',
  productPrice: 199000,
  productImage: require('../../assets/images/ventilador.png'),
  productDescription: 'Circulador de aire 21"',
  productSubCategory: 19,
  productColor: 'Negro',
 },
 {
  productId: 9,
  productName: 'WURDEN',
  productPrice: 89000,
  productImage: require('../../assets/images/plancha.png'),
  productDescription: 'Plancha a Vapor 2000 W WIRON-1001CER',
  productSubCategory: 18,
  productColor: 'Negro',
 },
 {
  productId: 10,
  productName: 'GAMA',
  productPrice: 189000,
  productImage: require('../../assets/images/secadora.png'),
  productDescription: 'Secadora SE Ultra',
  productSubCategory: 18,
  productColor: 'Negro',
 },
 {
  productId: 11,
  productName: 'PHILIPS',
  productPrice: 139000,
  productImage: require('../../assets/images/depiladora.png'),
  productDescription: 'Depiladora con Cable Satinelle Essential BRE225 PHILIPS',
  productSubCategory: 21,
  productColor: 'Blanco',
 },
 {
  productId: 12,
  productName: 'BEURER',
  productPrice: 229000,
  productImage: require('../../assets/images/balanza.png'),
  productDescription: 'Balanza Digital',
  productSubCategory: 21,
  productColor: 'Negro',
 },
 {
  productId: 13,
  productName: 'BEURER',
  productPrice: 259000,
  productImage: require('../../assets/images/cepillo_limpieza_facial.png'),
  productDescription: 'Cepillo de Limpieza Facial',
  productSubCategory: 21,
  productColor: 'Blanco',
 },
 {
  productId: 14,
  productName: 'GIORGIO ARMANI',
  productPrice: 559000,
  productImage: require('../../assets/images/perfume_hombre.png'),
  productDescription: 'Giorgio Armani Acqua Di Gio Absolu 125 ml',
  productSubCategory: 21,
  productColor: 'Blanco',
 },
 {
  productId: 15,
  productName: 'CHANEL',
  productPrice: 619000,
  productImage: require('../../assets/images/perfume_mujer.png'),
  productDescription: 'N°5 Eau Première Vaporizador',
  productSubCategory: 25,
  productColor: 'Blanco',
 },
 {
  productId: 16,
  productName: 'AMERICAN CREW',
  productPrice: 78000,
  productImage: require('../../assets/images/crema_de_afeitar_hombre.png'),
  productDescription: 'Crema de afeitar Light Hold Texture Lotion',
  productSubCategory: 28,
  productColor: 'Blanco',
 },
 {
  productId: 17,
  productName: 'Maat',
  productPrice: 89900,
  productImage: require('../../assets/images/cojin_geometrico.png'),
  productDescription: 'Cojín Geométrico Black & White',
  productSubCategory: 31,
  productColor: 'Blanco',
 },
 {
  productId: 18,
  productName: 'Ferrand',
  productPrice: 89900,
  productImage: require('../../assets/images/copas.png'),
  productDescription: 'Set x 4 Copas Gin Ferrand',
  productSubCategory: 34,
  productColor: 'Blanco',
 },
 {
  productId: 19,
  productName: 'CRATE & BARREL',
  productPrice: 249500,
  productImage: require('../../assets/images/bowl.png'),
  productDescription: 'Bowl Swoop Mediano',
  productSubCategory: 34,
  productColor: 'Blanco',
 },
 {
  productId: 20,
  productName: 'SONY',
  productPrice: 249500,
  productImage: require('../../assets/images/audifonos.png'),
  productDescription: 'Audífonos Over Ear Bluetooth Sony WH-CH510',
  productSubCategory: 9,
  productColor: 'Azul',
 },
 {
  productId: 21,
  productName: 'USAMS',
  productPrice: 59000,
  productImage: require('../../assets/images/cargador.png'),
  productDescription: 'Cargador T34 Pared rápido PD 20W',
  productSubCategory: 6,
  productColor: 'Azul',
 },
 {
  productId: 22,
  productName: 'SONY',
  productPrice: 199000,
  productImage: require('../../assets/images/parlantes.png'),
  productDescription: 'Parlante Inalámbrico Bluetooth Sony SRS-XB13 Negro',
  productSubCategory: 9,
  productColor: 'Rosado',
 },

 {
  productId: 23,
  productName: 'DIOR',
  productPrice: 169000,
  productImage: require('../../assets/images/labial.png'),
  productDescription: 'Dior Labial Rouge',
  productSubCategory: 26,
  productColor: '525 Cherie - Metallic',
 },
 {
  productId: 24,
  productName: "L'ORÉAL PARIS",
  productPrice: 538000,
  productImage: require('../../assets/images/base_maquillaje.png'),
  productDescription: 'Base de Maquillaje Infallible Pro-Matte',
  productSubCategory: 26,
  productColor: '525 Cherie - Metallic',
 },
];
