export const products = [
 {
  id: 1,
  name: 'ELECTROLUX',
  price: 839000,
  image: require('../../assets/images/aspiradora.png'),
  description: 'Aspiradora 1200 W 440 W Succión',
  category: 'electrodomesticos',
  color: 'Negro',
 },
 {
  id: 2,
  name: 'KITCHENAID',
  price: 1699000,
  image: require('../../assets/images/batidora.png'),
  description: 'Batidora Artisan Metallic Chrome',
  category: 'electrodomesticos',
  color: 'Negro',
 },
 {
  id: 3,
  name: 'OSTER',
  price: 118000,
  image: require('../../assets/images/cafetera.png'),
  description: 'Cafetera 4 tazas BVSTDCDR5B',
  category: 'electrodomesticos',
  color: 'Negro',
 },
 {
  id: 4,
  name: 'GAMA',
  price: 89000,
  image: require('../../assets/images/cortapelo.png'),
  description: 'Clipper SE PRO Power 10',
  category: 'cuidado personal',
  color: 'Negro',
 },
 {
  id: 5,
  name: 'OSTER',
  price: 50509,
  image: require('../../assets/images/freidoraDeAire.png'),
  description: 'Freidora Oster de aire de 5.5 Litros CKSTAF55',
  category: 'electrodomesticos',
  color: 'Negro',
 },
 {
  id: 6,
  name: 'OSTER',
  price: 590000,
  image: require('../../assets/images/OriginalLicuadora.png'),
  description: 'Licuadora Kaliman 2 Vel + Pulso BLSTKAG Roja',
  category: 'electrodomesticos',
  color: 'Negro',
 },
 {
  id: 7,
  name: 'OSTER',
  price: 249000,
  image: require('../../assets/images/Multiolla.png'),
  description: 'Multiolla rápida electrica de 5,7 lts Oster®',
  category: 'electrodomesticos',
  color: 'Negro',
 },
 {
  id: 8,
  name: 'OSTER',
  price: 199000,
  image: require('../../assets/images/ventilador.png'),
  description: 'Circulador de aire 21"',
  category: 'hogar',
  color: 'Negro',
 },
 {
  id: 9,
  name: 'WURDEN',
  price: 89000,
  image: require('../../assets/images/plancha.png'),
  description: 'Plancha a Vapor 2000 W WIRON-1001CER',
  category: 'hogar',
  color: 'Negro',
 },
 {
  id: 10,
  name: 'GAMA',
  price: 189000,
  image: require('../../assets/images/secadora.png'),
  description: 'Secadora SE Ultra',
  category: 'hogar',
  color: 'Negro',
 },
];
