export const products = [
 {
  productId: 1,
  productName: 'ELECTROLUX',
  productPrice: 839000,
  productImage: require('../../assets/images/aspiradora.png'),
  productDescription: 'Aspiradora 1200 W 440 W Succión',
  productCategory: 'electrodomesticos',
  productColor: 'Negro',
 },
 {
  productId: 2,
  productName: 'KITCHENA',
  productPrice: 1699000,
  productImage: require('../../assets/images/batidora.png'),
  productDescription: 'batidora Artisan Metallic Chrome',
  productCategory: 'electrodomesticos',
  productColor: 'Negro',
 },
 {
  productId: 3,
  productName: 'OSTER',
  productPrice: 118000,
  productImage: require('../../assets/images/cafetera.png'),
  productDescription: 'Cafetera 4 tazas BVSTDCDR5B',
  productCategory: 'electrodomesticos',
  productColor: 'Negro',
 },
 {
  productId: 4,
  productName: 'GAMA',
  productPrice: 89000,
  productImage: require('../../assets/images/cortapelo.png'),
  productDescription: 'Clipper SE PRO Power 10',
  productCategory: 'cuproductIdado personal',
  productColor: 'Negro',
 },
 {
  productId: 5,
  productName: 'OSTER',
  productPrice: '505090.50',
  productImage: require('../../assets/images/freidoraDeAire.png'),
  productDescription: 'Freidora Oster de aire de 5.5 Litros CKSTAF55',
  productCategory: 'electrodomesticos',
  productColor: 'Negro',
 },
 {
  productId: 6,
  productName: 'OSTER',
  productPrice: 590000,
  productImage: require('../../assets/images/OriginalLicuadora.png'),
  productDescription: 'Licuadora Kaliman 2 Vel + Pulso BLSTKAG Roja',
  productCategory: 'electrodomesticos',
  productColor: 'Negro',
 },
 {
  productId: 7,
  productName: 'OSTER',
  productPrice: 249000,
  productImage: require('../../assets/images/Multiolla.png'),
  productDescription: 'Multiolla rápproductIda electrica de 5,7 lts Oster®',
  productCategory: 'electrodomesticos',
  productColor: 'Negro',
 },
 {
  productId: 8,
  productName: 'OSTER',
  productPrice: 199000,
  productImage: require('../../assets/images/ventilador.png'),
  productDescription: 'Circulador de aire 21"',
  productCategory: 'hogar',
  productColor: 'Negro',
 },
 {
  productId: 9,
  productName: 'WURDEN',
  productPrice: 89000,
  productImage: require('../../assets/images/plancha.png'),
  productDescription: 'Plancha a Vapor 2000 W WIRON-1001CER',
  productCategory: 'hogar',
  productColor: 'Negro',
 },
 {
  productId: 10,
  productName: 'GAMA',
  productPrice: 189000,
  productImage: require('../../assets/images/secadora.png'),
  productDescription: 'Secadora SE Ultra',
  productCategory: 'hogar',
  productColor: 'Negro',
 },
];
